app_1/urls.py
from django.contrib import admin
from django.urls import path,include
from app_1 import views 

app_name = "app_1"

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
]

urls_example/urls.py
from django.contrib import admin
from django.urls import path,include
from app_1 import views 

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/',views.user_logout,name = 'logout'),
    path('special/',views.special,name = 'special'),
    path('app_1/',include('app_1.urls')),
    path('admin/', admin.site.urls),
]

app_1/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class ProfileUserInfo(models.Model):

    user = models.OneToOneField(User,on_delete = models.PROTECT)

    portfolio_site = models.URLField(blank=True)

    profile_pic =  models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

app_1/forms.py
from django import forms
from django.contrib.auth.models import User
from app_1.models import ProfileUserInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ['username','email','password']

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = ProfileUserInfo
        fields = ['user','portfolio_site','profile_pic']

app_1/views.py
from django.shortcuts import render
from app_1.forms import UserProfileInfoForm,UserForm
from django.urls import reverse
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
# Create your views here.

def index(request):
    context_dict = {'text':'Hello world', 'number':100}
    return  render(request,'app_1/index.html',context_dict)

def other(request):
    return render(request,'app_1/other.html')

def relative(request):
    return render(request,'app_1/relative_url_templates.html')
   
def register(request):
    registered = False
    if request.method == "POST" :
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()


            ##user = user_form.save(commit=False)
            profile=profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
            pass
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    
    return render(request,'app_1/registrations.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

@login_required 
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
@login_required 
def special(request):
    return HttpResponse("You are logged i ") 
def user_login (request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password') 

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))


            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Some tried to login and faild")
            print("User : {} and password:{}".format(username,password))
            return HttpResponse("in valid login details supplied!")
    else:
        return render(request,'app_1/login.html',{})

templates/app_1/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}"/>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'index'%}">BRAND <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'admin:index' %}">ADMIN</a>
            <a class="nav-item nav-link" href="{% url 'app_1:other'%}">OTHER</a>
            <a class="nav-item nav-link" href="{% url 'app_1:register' %}">Register</a>
            {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'logout'%}">Logout</a>
            {% else %}
              <a class="nav-item nav-link" href="{% url 'app_1:user_login' %}">Login</a>
            {% endif %}
            <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true"> </a>
          </div>
        </div>
    </nav>
<div class="container">
{% block body_block %}
{% endblock %}
</div>
</body>
</html>

templates/app_1/index.html
<!DOCTYPE html>
{% extends "app_1/base.html" %}


{% block body_block %}
    <h1> WELCOME TO INDEX! </h1>
    <h2>This an example of INDEX inheritance !</h2>
   <h3> {{ text| cut:'Hello' }}</h3>
    <h4> {{ number|add:"99" }}</h4>
    {% endblock%}
 

templates/app_1/login.html
{% extends "app_1/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'app_1:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username : </label>
    <input type="text" name="username" placeholder="Enter user name">
    <label for="password">Password</label>
    <input type="password" name="password" >
    <input type="submit" value="Login">
</form>
</div>

{% endblock%}

templates/app_1/other.html
<!DOCTYPE html>
{% extends "app_1/base.html" %}
{% block body_block %}

    <h1> WELCOME TO OTHER! </h1>
    <h2>This an example of templates inheritance !</h2>
    {% endblock%}
 

templates/app_1/registrations.html
<!DOCTYPE html>
{% extends "app_1/base.html" %}

{% load staticfiles %}
{% block body_block %}
<div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the Form: </h3>
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        {% endif %}
        <input type="submit" name="" value="Register">
    </form>

    {% endblock %}

templates/app_1/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>RELATIVE URLS</title>
</head>
<body>
    <h1> WELCOME TO RELATIVE URLS TEMPLEATES! </h1>
    <a href="{% url 'app_1:other'%}">OTHER PAGE</a>
    <a href="{% url 'admin:index'%}">ADmin PAGE</a>
    <a href="{% url 'index'%}">INDEX PAGE</a>
</body>
</html>